In [1]:
import numpy as np

In [2]:
A = np.array([10, 20, 30])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [3]:
output = np.zeros(len(A), dtype=int)

for i in range(len(A)):
    ai = A[i]
    bi = B[i]
    for bij in bi:
        output[i] += ai * bij

output

array([  60,  440, 1140])

In [4]:
def fun(args):
    i, (ai, bi) = args
    return sum(map(lambda bij: ai * bij, bi))

np.fromiter(map(fun, enumerate(zip(A, B))), dtype=int)

array([  60,  440, 1140])

In [5]:
np.array([sum(ai * bij for bij in bi) for i, (ai, bi) in enumerate(zip(A, B))])

array([  60,  440, 1140])

In [6]:
class ABProduct:
    def __init__(self, ai, bij):
        self._value = ai * bij

    def __add__(one, two):
        out = ABProduct.__new__(ABProduct)
        out._value = int(one) + int(two)
        return out
    
    __radd__ = __add__

    def __int__(self):
        return int(self._value)

output = []

for ai, bi in zip(A, B):
    output.append(sum([ABProduct(ai, bij) for bij in bi]))

np.array(output, dtype=int)

array([  60,  440, 1140])

In [7]:
class Fun:
    def __call__(self, args):
        i, (ai, bi) = args
        return sum(map(lambda bij: ai * bij, bi))

np.fromiter(map(Fun(), enumerate(zip(A, B))), dtype=int)

array([  60,  440, 1140])

In [8]:
np.sum(A[:, np.newaxis] * B, axis=1)

array([  60,  440, 1140])

In [12]:
np.einsum("i,ij -> i", A, B)

array([  60,  440, 1140])